export const metadata = {
  title: "Terms of Service — GradeIQ",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-paper text-ink font-body">
      <header className="border-b border-line px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <a href="/" className="font-display text-2xl text-ink">
            GradeIQ
          </a>
          <a href="/" className="font-mono text-xs text-slate hover:text-moss transition-colors">
            ← Back
          </a>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-6 py-14">
        <h1 className="font-display text-4xl mb-2">Terms of Service</h1>
        <p className="font-mono text-xs text-slate/60 mb-12">Last updated: July 18, 2026</p>

        <div className="space-y-10 font-body text-sm leading-relaxed text-ink">
          <section>
            <h2 className="font-display text-xl mb-3">1. Informational purposes only</h2>
            <p className="mb-3">
              GradeIQ provides AI-generated condition assessments, grader comparisons, expected
              net ROI estimates, and related data (collectively, the &quot;Service&quot;) for
              general informational purposes only. Nothing on GradeIQ constitutes financial,
              investment, legal, tax, or professional advice of any kind, and the Service is not
              intended to be a substitute for your own independent research and judgment.
            </p>
            <p>
              Trading cards, including graded trading cards, are collectibles whose value can be
              volatile and speculative. You should not make any purchasing, submission, or sale
              decision based solely on information provided by GradeIQ.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl mb-3">2. No guarantee of outcomes</h2>
            <p className="mb-3">
              GradeIQ does not guarantee, warrant, or promise any particular grading outcome
              (including the grade a submitted card will actually receive from any grading
              company), any particular sale price, or any particular return on investment (ROI).
              Vision-based condition assessments are generated by an AI model reviewing photographs
              and can differ from the assessment a professional human grader would reach on the
              physical card.
            </p>
            <p>
              Gem rates, population data, market prices, and sale comparables displayed on GradeIQ
              are estimates derived from third-party sources and historical data, and are not a
              prediction of future results.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl mb-3">3. You assume all risk</h2>
            <p>
              You are solely responsible for, and assume all risk arising from, any decision to
              purchase, submit for grading, hold, or sell a trading card, whether or not that
              decision was informed by information from GradeIQ. This includes decisions made
              using the Buy Signals page, IQ Score, max buy price calculations, and any
              recommendation shown in scan results.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl mb-3">4. Data usage and storage</h2>
            <p className="mb-3">
              When you use the Service, we collect and store the information described in our{" "}
              <a href="/privacy" className="text-moss underline underline-offset-2">
                Privacy Policy
              </a>
              , including your account information, uploaded card photos, and scan history. We use
              this data to operate the Service, including running AI condition assessments and
              maintaining your scan history and portfolio records, and to improve the accuracy of
              our AI analysis over time.
            </p>
            <p>
              By uploading card photos, you represent that you have the right to upload them and
              to have them analyzed by our AI vision provider as described in the Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl mb-3">5. Data accuracy disclaimer</h2>
            <p>
              GradeIQ&apos;s gem rate, population, and market pricing data is collected via
              automated scraping and third-party APIs on a periodic (typically nightly) basis. As
              a result, this data may be delayed, incomplete, or inaccurate at any given moment,
              and may not reflect the most current population counts, sale prices, or market
              conditions. We make reasonable efforts to keep this data current but do not warrant
              its accuracy, completeness, or timeliness.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl mb-3">6. Limitation of liability</h2>
            <p>
              To the fullest extent permitted by law, GradeIQ and its operators will not be liable
              for any direct, indirect, incidental, consequential, or special damages, including
              but not limited to lost profits, lost opportunity, or financial losses arising from
              or related to: (a) any grading, purchasing, or selling decision made using the
              Service; (b) inaccurate, delayed, or incomplete data displayed by the Service; or (c)
              any AI-generated assessment that differs from an actual professional grading outcome.
              The Service is provided &quot;as is&quot; and &quot;as available&quot; without
              warranties of any kind, express or implied.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl mb-3">7. Intellectual property</h2>
            <p className="mb-3">
              You retain full ownership of the card photos you upload to GradeIQ. By uploading a
              photo, you grant GradeIQ a limited, non-exclusive license to store, process, and
              analyze that photo (including sending it to our AI vision provider) solely for the
              purpose of providing the Service to you.
            </p>
            <p>
              The GradeIQ name, logo, website design, and underlying software are the property of
              GradeIQ and may not be copied, reproduced, or used without permission.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl mb-3">8. Account termination</h2>
            <p>
              You may stop using the Service and request deletion of your account at any time (see
              the Privacy Policy for how). We reserve the right to suspend or terminate your
              account if you violate these Terms, misuse the Service, or engage in activity that
              we reasonably believe is fraudulent, abusive, or harmful to GradeIQ or other users.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl mb-3">9. Changes to these terms</h2>
            <p>
              We may update these Terms from time to time. If we make material changes, we will
              update the &quot;Last updated&quot; date above. Continued use of the Service after
              changes take effect constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl mb-3">10. Governing law</h2>
            <p>
              These Terms are governed by the laws of the State of California, without regard to
              its conflict of law principles. Any dispute arising from these Terms or the Service
              will be subject to the exclusive jurisdiction of the state and federal courts located
              in California.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl mb-3">11. Contact</h2>
            <p>
              Questions about these Terms can be sent to{" "}
              <a href="mailto:legal@gradeiq.net" className="text-moss underline underline-offset-2">
                legal@gradeiq.net
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
